CREATE TABLE OTP (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    MOBILE VARCHAR(255) NOT NULL,
    SESSION VARCHAR(255) NOT NULL,
    OTP VARCHAR(255) NOT NULL,
    EXPIRY_TIME DATETIME2 NOT NULL,
    CREATED_TIME DATETIME2 NOT NULL,
    USED_TIME DATETIME2,
    USED BIT NOT NULL,
    ATTEMPTS INT NOT NULL
);